[build]
builder="dockerfile"
dockerfilepath="C:\Users\User\source\repos\InventoryAPI\InventoryAPI\Dockerfile"

[deploy]
startCommand="./InventoryApi.dll"
restartPolicyType="always"
healthcheckPath="health"